### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by peternewman** [InsanityRadio/automix#2]
This is awesome, or maybe I should say insane! :laughing: 

You should add it and some of your other code to the EBU Awesome Broadcasting list, probably under radio production but it's on the edge of video too:
https://github.com/ebu/awesome-broadcasting/

**Comment by Jamie0** [comment]
Thank you so much for the feedback (and sorry for the late reply from the team)! We've done just that :) I'm not entirely sure how compatible it is with the current generation of ATEM hardware but I'm sure it wouldn't take much tweaking where needed!
